"""add pricing recommendations table

Revision ID: 0551322bc312
Revises: 50d8ee5a9659
Create Date: 2025-09-30 22:37:05.165193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0551322bc312'
down_revision: Union[str, None] = '50d8ee5a9659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('route', sa.String(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('optimal_price', sa.Float(), nullable=False),
    sa.Column('recommended_price', sa.Float(), nullable=True),
    sa.Column('competitor_price', sa.Float(), nullable=True),
    sa.Column('current_revenue', sa.Float(), nullable=True),
    sa.Column('optimal_revenue', sa.Float(), nullable=True),
    sa.Column('uplift_percent', sa.Float(), nullable=True),
    sa.Column('estimated_demand', sa.Float(), nullable=True),
    sa.Column('distance_miles', sa.Float(), nullable=True),
    sa.Column('passengers', sa.Integer(), nullable=True),
    sa.Column('market_share_largest', sa.Float(), nullable=True),
    sa.Column('market_share_lowest_fare', sa.Float(), nullable=True),
    sa.Column('is_applied', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_recommendations_created_at'), 'pricing_recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_pricing_recommendations_id'), 'pricing_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_pricing_recommendations_route'), 'pricing_recommendations', ['route'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pricing_recommendations_route'), table_name='pricing_recommendations')
    op.drop_index(op.f('ix_pricing_recommendations_id'), table_name='pricing_recommendations')
    op.drop_index(op.f('ix_pricing_recommendations_created_at'), table_name='pricing_recommendations')
    op.drop_table('pricing_recommendations')
    # ### end Alembic commands ###
